name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  injection:
    path: ../injection
  repository:
    path: ../repository
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
