name: injection
description: injection package.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4
  meta: ^1.15.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  service:
    path: ../service
  shared_preferences: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
